language: python

python:
  - "3.6"

services:
  - docker

before_script: pip install docker-compose

install:
  - pip install -r requirements.txt

script:
  - docker-compose run data-builder sh -c "pytest"
