version: "3"

services:
  data-builder:
    build: "./DWDateTime"
    # volumes: # we'll let VSCode handle these for local development
    #   - ./:/app
    command: sh -c "python /app/main.py"
    # these commands are overridden when using docker-compose run <service> sh -c "<command>"
    # for example: docker-compose run data-builder sh -c "pytest"
